### ISSUE TITLE
Migrate to github merge queues

### ISSUE THREAD

**Issue by Niki4tap** [rust-marker/marker#129]
On May 1, 2023 [bors-ng](https://github.com/bors-ng/bors-ng) [became deprecated](https://bors.tech/newsletter/2023/05/01/tmib-76/).

> The main reason for this is that GitHub has a [built-in merge queue](https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/) now that is publicly available... More importantly, there’s a bunch of bugs in bors-ng that we can’t fix, but they can.

Github merge queues seem overall better than bors-ng due to its integration with the service itself, and unfortunately the public instance [already throws warnings](https://github.com/bors-ng/bors-ng/commit/7430c3ad5b078d6c1d72c77e79a3a4ecbc28a3d2) and will eventually go down. This is acceptable for the projects that self-host a bors instance and cannot change their workflow, but I think in this project we can try new features.

More on merge queues [here](https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/) and [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).

**Comment by xFrednet** [comment]
In the bors-ng forum it was said, that bors will most likely continue to work, until GH's merges queues are stabilizes. This issue should definitely be addressed before then, but for now I'm focussing on other issues.

The main holdup on merging #132 is that the `bors try` comment would be lost. That one is super useful, since the normal CI only runs on linux, while the bors tests run on windows, linux, and macos.
