### ISSUE TITLE
Error: NoTargetDir when running in a workspace with rust-toolchain `1.65.0` version

### ISSUE THREAD

**Issue by Veetaha** [rust-marker/marker#188]
The error is simply
```
$ cargo marker
Error: NoTargetDir
```
Our cargo workspace is sitting on an older version of rust toolchain, although we are planning to upgrade soon, but the error is not informative, it doesn't show what actually went wrong. Only by inspecting the code of `cargo-marker` and experimenting I figured out the rust version was causing this.

To reproduce this you may create a crago workspace with `rust-toolchain` file with `1.65.0` in it.

The version of cargo-marker is `0.1.1` and `marker_lints` is `0.1.1` as well

**Comment by xFrednet** [comment]
Thank you for the issue! The error handling in `cargo_marker` really has to be improved. I believe that one comes from the fact that it can't find the `target` directory. It expects it to be right next to the `Cargo.toml` file. It's supposed to be a sanity check to prevent markers from creating unwanted filed. However, currently it doesn't take into account that the target directory can be changed for cargo. (Put that on the ToDo list ^^)

Could you try creating a directory called `target` next to the `Cargo.toml` file?

The `rust-toolchain` file should not affect marker. The driver needs a specific nightly version, but Marker tires to hide this. `cargo marker` can be called with any version, and should only internally switch to the nightly version to compile the lints and run the driver. To the project, it should look like any other cargo command. This solution is not perfect, but the best I could come up with in the meantime.

**Comment by Veetaha** [comment]
@xFrednet the target directory exists. My setup is no different from any other cargo workspace in this regard.
You may check for yourself, but running the following commands:
```bash
$ cargo new foo
     Created binary (application) `foo` package
$ cd foo
$ echo 1.65.0 > rust-toolchain
$ cargo build
   Compiling foo v0.1.0 (/home/veetaha/junk/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
$ cargo marker --lints 'marker_lints = "0.1.1"'
Error: NoTargetDir
```

**Comment by xFrednet** [comment]
Interesting, I'll investigate this! :)

**Comment by NathanFrasier** [comment]
FWIW: I was looking into using marker for a large app at work, and ran into the same issue, I made a minimal clone of the marker test crate and removed all of the testing code, and running `cargo marker` creates the same error. Our rust toolchain is `1.58.1` at the moment. I changed to 1.71.0 and re-ran cargo marker and it linted correctly.

**Comment by xFrednet** [comment]
Thank you for the feedback!

This will be fixed in the next version, planned for the next rust release. I plan to check for a `target` directory next to the `Cargo.toml` file and also add a configuration for it.

**Comment by NathanFrasier** [comment]
Doing a little digging and some good old fashioned `dbg!()` statement troubleshooting. it looks like this is due to the cargo metadata command invoking `rustc` with `--print=split-debuginfo` which lines up because I vaguely remember that only being stabilized recently. @xFrednet Am I wildly off base in saying the path forward is trying to get cargo-metadata to not pass that print flag? It seems like this wouldn't be a case where we need to bump the MSRV.

**Comment by xFrednet** [comment]
> Am I wildly off base in saying the path forward is trying to get cargo-metadata to not pass that print flag?

What path forwarding do you mean in this case?

If you're referring to the `cargo_path` used when `CargoMetadata` is [invoked](https://github.com/rust-marker/marker/blob/41eaf5b2155f882fbba836ac5b65a42ddf539a04/cargo-marker/src/backend/toolchain.rs#L81-L89), that path is mostly set to consistently use the same version of cargo for commands. Due to the way rustc's internals are wired, Marker sadly needs to run with nightly.

If you're asking why cargo uses `--print=split-debuginfo` internally, I'm not sure. I would guess that it already has infrastructure to read the split debug info, and it's easier to just reuse that code than to parse the console output of rustc.

---

The goal of the function, that throws the error, is to find the target directory. I used `CargoMetadata` because it seemed like the easiest approach. `cargo-marker` should have a low MSRV to allow all projects to use it. (This should be tested in CI, but that's a story for another time ^^)

I can think of the following solutions to investigate:
1. Try to figure out, if the called version of rustc can be overridden, it should work just fine if we instruct cargo to also use the nightly rustc version to fetch the debug info. (Try setting `RUSTUP_TOOLCHAIN` variable in [`MetadataCommand::env`](https://docs.rs/cargo_metadata/0.17.0/cargo_metadata/struct.MetadataCommand.html#method.env))
2. Manually invoke `cargo metadata` with `marker*::Toolchain::cargo_command()` and use `cargo_metadata` to parse the output.
3. Determine the target directory differently (Maybe check for a `./target` folder)
4. Allow the user to manually specify the target directory.

I believe 1 and 2 would be the best solutions if they work. We might also want to investigate if `cargo-marker` has other faulty calls to `MetadataCommand` which were just hidden by this error. I would also like option 4 to be implemented at one point, but that can very well be new issue :)

---

Btw. since you started digging though Marker, I've started writing some contributor documentation: https://github.com/rust-marker/marker/pull/199 Not sure if it contains any additional information for you, since you already got the project running, but it might still be useful. Thank you for helping with this issue!

**Comment by NathanFrasier** [comment]
> What path forwarding do you mean in this case?

Ah, I'm sorry, I need to be more aware of my expressions, not everyone online uses my local jargon.
I could have been clearer with "Am I correct in assuming that the way to resolve this bug is..." You have answered that question despite my poor phrasing.

I'll be looking into option #1 first, (or maybe #2 if that's just not possible) as it seems extremely likely to me that there are other places this inconsistency has occurred and that the find target dir is just the one that happened to crop up first.

**Comment by xFrednet** [comment]
> Ah, I'm sorry. I need to be more aware of my expressions, not everyone online uses my local jargon.

"The path forward" is a common phrase in English, so please continue using it, also on GH. My mind was just so focussed on file paths, that it didn't consider the sentence as a whole ^^

This bug is now fixed with your PR. I've created a new issue #205 for the fourth option, to allow users to specify the target directory manually :)
