### ISSUE TITLE
Support incompatible rustc versions

### ISSUE THREAD

**Issue by HKalbasi** [rust-marker/marker#33]
Drivers that are not rustc itself, currently need to use the compiler that are compiled with to compile user lints, not the compiler installed on the user system. Solving this probably needs a more detailed C api over the interface traits. Not that it needs to be addressed immediately, just something to consider in long-term.

**Comment by HKalbasi** [comment]
Will be fixed by #30 ?

**Comment by xFrednet** [comment]
The nightly version is mainly needed for the driver. In an ideal world, the driver will be moved into rust-lang/rust at one point. Even then, I believe we'll mostly use the nightly version, since the api will need to be updated with the latest addition to the language. But as you say that's far off, I can also imagine moving the driver to a different repo, if we have multiple ones.

> Will be fixed by https://github.com/rust-linting/rust-linting/pull/30 ?

No, that PR just uses a lot of undefined behavior when calling into linter-crates

**Comment by HKalbasi** [comment]
Hmm, I didn't understand how this relates to nightly. I think it is possible to make some driver (not the rustc driver implemented in this repository) in stable (correct me if I'm wrong). The problem this issue mentions is, if I build my driver (say, rust-analyzer) with stable 1.60 and publish binaries for it, I can't use the stable compiler 1.70 installed on user's machine to compile their lints, and I need to download 1.60 on their system (I'm not even sure even that works. Is it ok to use two compiler with the exact same versions, but on different machines?)

**Comment by xFrednet** [comment]
Ahh, okay, then I misunderstood you. Hopefully, now I got the question right:

> The problem this issue mentions is, if I build my driver (say, rust-analyzer) with stable 1.60 and publish binaries for it, I can't use the stable compiler 1.70 installed on user's machine to compile their lints, and I need to download 1.60 on their system

The answer is a bit more complicated. The driver will later call lint-crates over a C interface and ABI. Since that ABI is stable, you can combine any driver with any lint-crate iff they use the same version of the `liner_api` crate. So in theory, it would be no problem, to do this.

Now, in practice, we'll have to keep the `linter_api` crate up to date with any semantic related changes to rustc. Meaning that there will be most likely a new `linter_api` version with every rust version. So, the 1.60 driver would use `linter_api = 1.60.0`. If the lint crate uses the same version, then everything is fine. Otherwise, the driver will terminate with a warning, that the lint-crate API version doesn't match the driver version.

If I can indulge in some wishful thinking, then we would actually distribute `cargo-linter` and `linter_driver_rustc` with rustup. Then the driver would always have the same version as the local compiler. Also note, that currently `cargo-liner` is responsible for compiling the lint-crates. For rust-analyzer we might push the responsibility of compiling the crates to somewhere else, but currently this is done by us and not the user. Partially to take care of this :)

Does that answer your question?

**Comment by xFrednet** [comment]
Also, just a side thought, the rustc driver is also a full compiler that can create binaries, so even if the user only has that driver, it's possible to compile the linter-crates. This, however, might not be the case for other drivers like the ra one.

**Comment by HKalbasi** [comment]
> The driver will later call lint-crates over a C interface and ABI. Since that ABI is stable, you can combine any driver with any lint-crate iff they use the same version of the liner_api crate. So in theory, it would be no problem, to do this.

But at least now it isn't the case, right? Because we are sending `&dyn` pointers as arguments of C functions, and they are `repr(rust)` and will break between different compiler versions (and even different machines?).

> Now, in practice, we'll have to keep the linter_api crate up to date

Here you mean that hir and ast datatypes will get more fields and variants over time, and because ABI problems, even minor versions can cause breakage, right? I think this problem is more tolerable, since the version of compiler which compiles the lint doesn't matter here (so no need to change toolchain), and the driver is in control of the compile process of lints, so it can use it's own version of `linter_api` as long as user's lint doesn't use a new thing from higher versions.

> For rust-analyzer we might push the responsibility of compiling the crates to somewhere else, but currently this is done by us and not the user.

I imagine that r-a controls the compilation of lints in r-a as well. I just wanted to not use the toolchain that r-a is built with to compile lints.

**Comment by xFrednet** [comment]
> But at least now it isn't the case, right? Because we are sending `&dyn` pointers as arguments of C functions, and they are `repr(rust)` and will break between different compiler versions (and even different machines?).

`repr(rust)` can even break between different compiler runs. That's why https://github.com/rust-linting/rust-linting/issues/8 is currently my prio 1. #30 reworks the `driver -> lint-crate` direction. And I'm currently working on the `lint-crate -> driver` direction on my dev branch. That's also why I suggested you wait until that is merged, as it reworks a big part of the driver interaction.

> Here you mean that hir and ast datatypes will get more fields and variants over time, and because ABI problems, even minor versions can cause breakage, right?

That's sadly true, but there is no good way around that. If everything goes well, it should only require the recompilation of the lint crates. There might be a good way around that, but ABI is not my area of expertise.

> I imagine that r-a controls the compilation of lints in r-a as well. I just wanted to not use the toolchain that r-a is built with to compile lints.

Okay, that should be no/less of a problem once the driver rework PR landed. Then the AST items still need to be `repr(C)` and reworked for more lazy evaluating, but that's a story for another time and shouldn't block the initial tests :)

**Comment by xFrednet** [comment]
Hey :wave: It has been a while ^^ The repo currently relies on a fixed toolchain version, mostly to allow the in tree development of the rustc driver and to use that driver for UI tests. However, the CI now tests that the `marker_api`, `marker_utils`(WIP) and `cargo_marker` crates all compile on stable. Once they're available on crates.io, it should allow other drivers to pick their development version freely. The `marker_adapter` crate currently uses nightly, for the `lint_reasons` feature, but we can move that crate to stable as well.

The rustc driver sadly requires a pinned toolchain version, and there is little we can do. The hope is that Marker will at one point gain similar privileges to Clippy, that it's built and provided as part of the stable toolchain. But that's par in the future. For now, we have `cargo_marker` which allows the automated installation of the toolchain and the driver. The nightly version requirement should no longer be noticeable from the POV of an end user :)

Do you think that covers this issue? :)

**Comment by HKalbasi** [comment]
> Hey wave It has been a while ^^

Hey! Yes, nice to see marker progressed so much.

> CI now tests that the marker_api, marker_utils(WIP) and cargo_marker crates all compile on stable.

That's great!

> Once they're available on crates.io, it should allow other drivers to pick their development version freely.

How the version of `marker_adapter` of the driver relates to the version of `marker_api` of the lint crates? Should it be exactly equal, or semver compatible, or there sis no restriction?

> Do you think that covers this issue? :)

Yes, now that the ABI boundary is `#[repr(C)]` I think there would be no requirement to compiling the driver with the same version of lints. So I will close this issue.

**Comment by xFrednet** [comment]
> Hey! Yes, nice to see marker progressed so much.

Thank you! I'm hoping to start if the first user tests/lints some time this year. Btw. Congratulations on joining the rust-analyzer team!

A side note, in case it's interesting: Right now, I'm still mainly focussed on rustc as a backend. However, before the official first stable version, I'm hoping to get some input on the API from the RA perspective.

> How the version of `marker_adapter` of the driver relates to the version of `marker_api` of the lint crates? Should it be exactly equal, or semver compatible, or there sis no restriction?

It's likely that the internal representation of the API will be adjusted over time, for example due to new language features or some internal restructuring. Every crate that relies on `marker_api` (including `marker_adapter`) should be compiled with the same version, to ensure compatibility. I plan to release a new version of all crates every 6 weeks with a new rust version. The actually used API version will be set by the driver when the lint crates are compiled. Updating/using a newer API version should always be possible, without breaking the lint crates :)
