### ISSUE TITLE
Cleanup / Decide how to represent empty generics arguments

### ISSUE THREAD

**Issue by xFrednet** [rust-marker/marker#85]
While refactoring rustc's driver, I noticed that the API currently has two representations for an item/path without generic arguments.
1. The `GenericsArgs` struct is wrapped in an `Option` making it clear whether they're empty or not
2. The `GenericsArgs` are constructed with an empty slice inside them. 

Rustc also uses both of these representations. I'm not sure which one is simpler for normal users. We could just add a method `is_empty()` to `GenericsArgs`. Not having them wrapped in an extra option could be nice for lints, that want to check for specific generics :)

**Comment by Niki4tap** [comment]
I don't think we should wrap them in an `Option`, `GenericArgs` with `is_empty()` method should be better in my opinion. Wrapping in an `Option` seems like a weird indirection, since you can represent the same state without it by just constructing it with an empty slice. Also, this doesn't matter a lot, but `Option<T>` a bit more memory to store than just `T`.
